name: CD Backend (Render Deploy Hook)
on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render deploy
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          if [ -z "$RENDER_DEPLOY_HOOK" ]; then
            echo "Missing RENDER_DEPLOY_HOOK secret. Please add it in repo settings."; exit 1;
          fi
          curl -fsS -X POST "$RENDER_DEPLOY_HOOK"
