name: Deploy Frontend to GitHub Pages
on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Survivor
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: Survivor/yarn.lock

      - name: Create .env for Vite
        run: |
          echo "VITE_BACKEND_URL=${{ secrets.VITE_BACKEND_URL }}" > .env

      - run: yarn install --frozen-lockfile || yarn install
      - run: npm install react-is
      - run: yarn add react-markdown remark-gfm
      - run: yarn build

      - name: Add SPA fallback
        run: cp dist/index.html dist/404.html || true

      - uses: actions/upload-pages-artifact@v3
        with:
          path: Survivor/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
